### ISSUE TITLE
Regarding eagle453's repository

### ISSUE THREAD

**Issue by servusdei2018** [fluhus/beatnik#1]
Hello @fluhus ,

This is a great repository you've got here! I found eagle453's repository when I was browsing Go repositories for "programming languages," and a musical programming language leaped right out. I didn't know he copied from you, but I'm glad to thank the right person.

-@servusDei2018

**Comment by fluhus** [comment]
Hey @servusDei2018 , thanks for getting back to me!

I use beatnik for my music production and would love to see others benefit from it. I welcome feedback, suggestions and collaboration.

Would you like to open an issue for loops? Also explain a bit how you'd like to use it so I can design a good solution.

**Comment by servusdei2018** [comment]
Sure, no problem :) I'll open the issue for loops right away.
