### ISSUE TITLE
include get-started section

### ISSUE THREAD

**Issue by truj** [fluhus/beatnik#3]
Add a chapter in the readme file that describes what's needed to run the program.
E.g.
- clone the repository like this: ...
- install go
- compile the source like this: ...
- run the program like this: ...

**Comment by fluhus** [comment]
Thank you for your suggestion!
I will add a section like that. I will also add compiled binaries to the releases tab so that people don't have to compile things themselves.

**Comment by fluhus** [comment]
Hi, please take a look at the new [getting started](https://github.com/fluhus/beatnik#getting-started) section.

Happy for feedback.

**Comment by truj** [comment]
Great, much better.
For the linux version you could maybe also mention to use `chmod +x` and `./` - but not that important.

**Comment by fluhus** [comment]
Good point.
Do you know how I can make them executable to begin with (compiling on windows)?

**Comment by fluhus** [comment]
I think I solved it.
Can you check that the new [release](https://github.com/fluhus/beatnik/releases) works for you without having to run chmod?

**Comment by truj** [comment]
Don't know if i understand the question correctly.
On Windows I guess they are already executable (however I don't use Windows).
On Linux:
```
chmod +x btnk
chmod +x gui
```
And executing:
```
./btnk file1.btn file2.btn
./gui
```
Or move them to e.g. /usr/local/bin:
```
su
mv btnk /usr/local/bin
mv gui /usr/local/bin
```
Then `./` is not needed any more for execution.

**Comment by fluhus** [comment]
See my last response ^^
(in case you missed it since we posted at the same time)

**Comment by truj** [comment]
Yes, indeed I missed your response.
It works now without chmod.

**Comment by fluhus** [comment]
Great!
The part about moving to /usr/local/bin depends on personal preference and permissions, so I think it's out of scope for this guide.
